module.exports = {
  primary: {
    50: "rgb(var(--dgs-color-primary-50) / <alpha-value>)",
    100: "rgb(var(--dgs-color-primary-100) / <alpha-value>)",
    200: "rgb(var(--dgs-color-primary-200) / <alpha-value>)",
    300: "rgb(var(--dgs-color-primary-300) / <alpha-value>)",
    400: "rgb(var(--dgs-color-primary-400) / <alpha-value>)",
    500: "rgb(var(--dgs-color-primary-500) / <alpha-value>)",
    600: "rgb(var(--dgs-color-primary-600) / <alpha-value>)",
    700: "rgb(var(--dgs-color-primary-700) / <alpha-value>)",
    800: "rgb(var(--dgs-color-primary-800) / <alpha-value>)",
    900: "rgb(var(--dgs-color-primary-900) / <alpha-value>)",
  },
  secondary: {
    50: "rgb(var(--dgs-color-secondary-50) / <alpha-value>)",
    100: "rgb(var(--dgs-color-secondary-100) / <alpha-value>)",
    200: "rgb(var(--dgs-color-secondary-200) / <alpha-value>)",
    300: "rgb(var(--dgs-color-secondary-300) / <alpha-value>)",
    400: "rgb(var(--dgs-color-secondary-400) / <alpha-value>)",
    500: "rgb(var(--dgs-color-secondary-500) / <alpha-value>)",
    600: "rgb(var(--dgs-color-secondary-600) / <alpha-value>)",
    700: "rgb(var(--dgs-color-secondary-700) / <alpha-value>)",
    800: "rgb(var(--dgs-color-secondary-800) / <alpha-value>)",
    900: "rgb(var(--dgs-color-secondary-900) / <alpha-value>)",
  },
  success: {
    50: "rgb(var(--dgs-color-success-50) / <alpha-value>)",
    100: "rgb(var(--dgs-color-success-100) / <alpha-value>)",
    200: "rgb(var(--dgs-color-success-200) / <alpha-value>)",
    300: "rgb(var(--dgs-color-success-300) / <alpha-value>)",
    400: "rgb(var(--dgs-color-success-400) / <alpha-value>)",
    500: "rgb(var(--dgs-color-success-500) / <alpha-value>)",
    600: "rgb(var(--dgs-color-success-600) / <alpha-value>)",
    700: "rgb(var(--dgs-color-success-700) / <alpha-value>)",
    800: "rgb(var(--dgs-color-success-800) / <alpha-value>)",
    900: "rgb(var(--dgs-color-success-900) / <alpha-value>)",
  },
  warning: {
    50: "rgb(var(--dgs-color-warning-50) / <alpha-value>)",
    100: "rgb(var(--dgs-color-warning-100) / <alpha-value>)",
    200: "rgb(var(--dgs-color-warning-200) / <alpha-value>)",
    300: "rgb(var(--dgs-color-warning-300) / <alpha-value>)",
    400: "rgb(var(--dgs-color-warning-400) / <alpha-value>)",
    500: "rgb(var(--dgs-color-warning-500) / <alpha-value>)",
    600: "rgb(var(--dgs-color-warning-600) / <alpha-value>)",
    700: "rgb(var(--dgs-color-warning-700) / <alpha-value>)",
    800: "rgb(var(--dgs-color-warning-800) / <alpha-value>)",
    900: "rgb(var(--dgs-color-warning-900) / <alpha-value>)",
  },
  error: {
    50: "rgb(var(--dgs-color-error-50) / <alpha-value>)",
    100: "rgb(var(--dgs-color-error-100) / <alpha-value>)",
    200: "rgb(var(--dgs-color-error-200) / <alpha-value>)",
    300: "rgb(var(--dgs-color-error-300) / <alpha-value>)",
    400: "rgb(var(--dgs-color-error-400) / <alpha-value>)",
    500: "rgb(var(--dgs-color-error-500) / <alpha-value>)",
    600: "rgb(var(--dgs-color-error-600) / <alpha-value>)",
    700: "rgb(var(--dgs-color-error-700) / <alpha-value>)",
    800: "rgb(var(--dgs-color-error-800) / <alpha-value>)",
    900: "rgb(var(--dgs-color-error-900) / <alpha-value>)",
  },
  gray: {
    50: "rgb(var(--dgs-color-gray-50) / <alpha-value>)",
    100: "rgb(var(--dgs-color-gray-100) / <alpha-value>)",
    200: "rgb(var(--dgs-color-gray-200) / <alpha-value>)",
    300: "rgb(var(--dgs-color-gray-300) / <alpha-value>)",
    400: "rgb(var(--dgs-color-gray-400) / <alpha-value>)",
    500: "rgb(var(--dgs-color-gray-500) / <alpha-value>)",
    600: "rgb(var(--dgs-color-gray-600) / <alpha-value>)",
    700: "rgb(var(--dgs-color-gray-700) / <alpha-value>)",
    800: "rgb(var(--dgs-color-gray-800) / <alpha-value>)",
    900: "rgb(var(--dgs-color-gray-900) / <alpha-value>)",
  },
  sky: {
    50: "rgb(var(--dgs-color-sky-50) / <alpha-value>)",
    100: "rgb(var(--dgs-color-sky-100) / <alpha-value>)",
    200: "rgb(var(--dgs-color-sky-200) / <alpha-value>)",
    300: "rgb(var(--dgs-color-sky-300) / <alpha-value>)",
    400: "rgb(var(--dgs-color-sky-400) / <alpha-value>)",
    500: "rgb(var(--dgs-color-sky-500) / <alpha-value>)",
    600: "rgb(var(--dgs-color-sky-600) / <alpha-value>)",
    700: "rgb(var(--dgs-color-sky-700) / <alpha-value>)",
    800: "rgb(var(--dgs-color-sky-800) / <alpha-value>)",
    900: "rgb(var(--dgs-color-sky-900) / <alpha-value>)",
  },
  violet: {
    50: "rgb(var(--dgs-color-violet-50) / <alpha-value>)",
    100: "rgb(var(--dgs-color-violet-100) / <alpha-value>)",
    200: "rgb(var(--dgs-color-violet-200) / <alpha-value>)",
    300: "rgb(var(--dgs-color-violet-300) / <alpha-value>)",
    400: "rgb(var(--dgs-color-violet-400) / <alpha-value>)",
    500: "rgb(var(--dgs-color-violet-500) / <alpha-value>)",
    600: "rgb(var(--dgs-color-violet-600) / <alpha-value>)",
    700: "rgb(var(--dgs-color-violet-700) / <alpha-value>)",
    800: "rgb(var(--dgs-color-violet-800) / <alpha-value>)",
    900: "rgb(var(--dgs-color-violet-900) / <alpha-value>)",
  },
  flamingo: {
    50: "rgb(var(--dgs-color-flamingo-50) / <alpha-value>)",
    100: "rgb(var(--dgs-color-flamingo-100) / <alpha-value>)",
    200: "rgb(var(--dgs-color-flamingo-200) / <alpha-value>)",
    300: "rgb(var(--dgs-color-flamingo-300) / <alpha-value>)",
    400: "rgb(var(--dgs-color-flamingo-400) / <alpha-value>)",
    500: "rgb(var(--dgs-color-flamingo-500) / <alpha-value>)",
    600: "rgb(var(--dgs-color-flamingo-600) / <alpha-value>)",
    700: "rgb(var(--dgs-color-flamingo-700) / <alpha-value>)",
    800: "rgb(var(--dgs-color-flamingo-800) / <alpha-value>)",
    900: "rgb(var(--dgs-color-flamingo-900) / <alpha-value>)",
  },
};
